### ISSUE TITLE
Is this gem still required?

### ISSUE THREAD

**Issue by tjwallace** [unamohq/sidekiq-oj#2]
I think `Oj` is used by default if you call `Oj.optimize_rails` in an initializer.

You can test this in `rails console`:
```
tracer = TracePoint.new(:c_call) { |tp| p [tp.lineno, tp.event, tp.defined_class, tp.method_id] }
tracer.enable { Sidekiq.dump_json(Time.current) }
# ...
# [22, :c_call, Oj::Rails::Encoder, :encode]
# ...
```

**Comment by rwojsznis** [comment]
Hi @tjwallace 

I guess it depends on your needs - `optimize_rails` does quite a few things under the hood ([reference](https://github.com/ohler55/oj/blob/d6780892db4af2dc51885a97255fc77e2e762c16/ext/oj/rails.c#L1057)) - and you might _not_ want to call it in your app for various different reasons - then this gem that patches very specific piece of code makes sense. Otherwise it does not 😉 .

**Comment by tjwallace** [comment]
Makes sense to me @emq, thanks for the info!
